// Daily movement library, based on public ACOG pregnancy & postpartum exercise guidance.
window.BLOOM_DAILY = window.BLOOM_DAILY || {};
BLOOM_DAILY.moves = {
  warm: [
    { n:'March in place', m:2, dose:'2 min', how:['Stand tall beside a counter or chair.','March, lifting knees to a comfortable height.','Swing your arms gently and breathe steadily.'], why:'Gently raises your heart rate and warms up hips and knees.' },
    { n:'Shoulder rolls & neck release', m:1, dose:'1 min', how:['Roll shoulders backward 10 times, then forward 10.','Tilt your ear toward each shoulder and hold 10 seconds.','Keep your jaw and belly relaxed.'], why:'Releases the upper-back tension that builds as your chest grows.' },
    { n:'Standing side reach', m:1, dose:'8 each side', how:['Stand with feet hip-width apart, knees soft.','Reach one arm overhead and lean slightly to the opposite side.','Return to centre and switch sides.'], why:'Opens the ribs so you can breathe deeper as your bump grows.' },
    { n:'Ankle circles & calf raises', m:2, dose:'10 each', how:['Hold a counter for balance.','Circle each ankle 10 times each way.','Rise onto your toes 10 times, lowering slowly.'], why:'Boosts circulation and can ease swollen ankles and leg cramps.' },
    { n:'Hip circles', m:1, dose:'8 each way', how:['Stand with feet wider than hips, hands on hips.','Draw slow, wide circles with your hips.','Switch direction halfway.'], why:'Loosens the hips and lower back before you load them.' },
    { n:'Arm circles', m:1, dose:'1 min', how:['Stretch arms out to the sides at shoulder height.','Make small circles forward for 30 seconds.','Reverse for 30 seconds.'], why:'Warms the shoulders you will use for lifting and carrying.' },
    { n:'Seated cat-cow', m:1, dose:'8 slow reps', how:['Sit on the edge of a sturdy chair, hands on knees.','Inhale: lift your chest and arch gently.','Exhale: round your back and drop your chin.'], why:'Mobilises the whole spine without getting on the floor.' },
    { n:'Heel-to-toe walk', m:2, dose:'2 min', how:['Walk slowly around the room, heel landing first.','Roll through to your toes with every step.','Keep your gaze forward and shoulders relaxed.'], why:'Warms the legs and practises steady balance as your centre of gravity shifts.' }
  ],
  cool: [
    { n:'Wide-knee child\'s pose', m:1, dose:'1 min', how:['Kneel with knees wide and big toes touching.','Sit back toward your heels and walk your hands forward.','Rest your chest on a pillow if your bump needs room.'], why:'Releases the lower back and lets the belly hang free.' },
    { n:'Seated butterfly stretch', m:1, dose:'1 min', how:['Sit tall with the soles of your feet together.','Let your knees fall out to a mild stretch only.','Breathe slowly; do not press your knees down.'], why:'Gently opens the inner thighs and hips. Your joints are looser now, so stay at mild tension.' },
    { n:'Wall calf stretch', m:2, dose:'30 s each side', how:['Hands on a wall, one foot stepped back.','Press the back heel down until you feel the calf stretch.','Hold, breathe, then switch legs.'], why:'Can reduce night-time leg cramps.' },
    { n:'Seated side stretch', m:1, dose:'30 s each side', how:['Sit cross-legged or on a chair.','Reach one arm up and over, lengthening your side.','Keep both sit bones grounded.'], why:'Makes space under the ribs, helping with breathlessness.' },
    { n:'Doorway chest opener', m:1, dose:'30 s', how:['Place forearms on each side of a doorway.','Step one foot through until you feel a chest stretch.','Keep your ribs down; no arching.'], why:'Counters the rounded shoulders that come with a heavier chest and feeding.' },
    { n:'Side-lying 360 breathing', m:2, dose:'10 breaths', how:['Lie on your left side with a pillow between your knees.','Breathe in through your nose so your ribs widen in all directions.','Breathe out slowly through your mouth, letting everything soften.'], why:'Calms your nervous system and teaches the breath you will use in labour.' },
    { n:'Chair figure-4 stretch', m:2, dose:'30 s each side', how:['Sit tall and cross one ankle over the opposite knee.','Hinge forward slightly from the hips with a long back.','Stop at a gentle stretch in the outer hip.'], why:'Eases buttock and sciatic-type pain.' },
    { n:'Upper-back round', m:1, dose:'3 × 10 s', how:['Clasp your hands in front at chest height.','Push your hands away and round your upper back.','Drop your chin and breathe into the space between your shoulder blades.'], why:'Relieves the ache between the shoulder blades.' }
  ],
  t1: [
    { n:'Brisk walk', m:15, dose:'15 min', how:['Walk at a pace where you can talk but not sing.','Swing your arms naturally.','Carry water and a snack if nausea is around.'], why:'The simplest way to hit the recommended 150 minutes a week of moderate activity.' },
    { n:'Chair squat', m:4, dose:'3 × 10', how:['Stand in front of a chair, feet hip-width apart.','Sit back until you lightly touch the seat.','Push through your heels to stand, breathing out as you rise.'], why:'Builds the leg strength you will rely on all pregnancy and in labour.' },
    { n:'Wall push-ups', m:3, dose:'3 × 10', how:['Hands on a wall at shoulder height, body in a straight line.','Bend your elbows to bring your chest toward the wall.','Push back, breathing out.'], why:'Strengthens your arms and chest for carrying a baby.' },
    { n:'Glute bridge', m:3, dose:'3 × 10', how:['Lie on your back, knees bent, feet flat.','Breathe out and lift your hips until your body is a straight line.','Lower slowly. First trimester only: from the second trimester, avoid lying flat on your back for long.'], why:'Strong glutes protect your lower back as your bump grows.' },
    { n:'Bird-dog', m:4, dose:'3 × 8 each side', how:['Start on hands and knees, back flat.','Reach one arm forward and the opposite leg back.','Hold 2 seconds, return, switch sides.'], why:'Trains deep core stability safely.' },
    { n:'Bent-over row with water bottles', m:3, dose:'3 × 12', how:['Hold a bottle in one hand; rest the other hand on a counter.','Hinge forward with a flat back.','Pull your elbow toward your hip, then lower.'], why:'Builds upper-back strength for posture.' },
    { n:'Side-lying clamshell', m:4, dose:'3 × 12 each side', how:['Lie on your side, knees bent, feet together.','Keeping your feet touching, lift your top knee.','Lower slowly; do not roll your hips back.'], why:'Strengthens the hip muscles that stabilise your pelvis.' },
    { n:'Kegel basics', m:3, dose:'10 slow + 10 quick', how:['Squeeze and lift as if stopping wind and urine at once.','Hold 3 to 5 seconds, then fully relax for as long.','Finish with 10 quick squeeze-and-release flicks.'], why:'A strong pelvic floor supports your growing uterus and helps prevent leaks.' },
    { n:'Stationary bike or swim', m:20, dose:'20 min', how:['Pick a steady, moderate pace.','Use the talk test: you should be able to hold a conversation.','Stop if you feel dizzy or overheated.'], why:'Low-impact cardio that is kind to your joints.' },
    { n:'Supported reverse lunge', m:4, dose:'2 × 8 each leg', how:['Hold a chair back for balance.','Step one foot back and lower gently.','Push through your front heel to return.'], why:'Builds single-leg strength and balance.' },
    { n:'Mini yoga flow', m:10, dose:'10 min', how:['Cat-cow on hands and knees for 1 minute.','Low lunge with hands on blocks, 30 seconds each side.','Goddess pose squat for 5 slow breaths, then repeat the flow.'], why:'Combines strength, mobility and calm breathing.' },
    { n:'Dance break', m:10, dose:'3 songs', how:['Put on three songs you love.','Move freely: side steps, arm swings, hip sways.','Keep it low-impact: one foot on the floor at all times.'], why:'Fun movement lifts your mood and energy on nauseous days.' }
  ],
  t2: [
    { n:'Walk with arm swings', m:20, dose:'20 min', how:['Walk at a talk-test pace.','Swing bent arms from the shoulders.','Wear supportive shoes; your feet may be wider now.'], why:'Keeps your heart and lungs strong and helps regulate blood sugar.' },
    { n:'Sumo squat', m:4, dose:'3 × 10', how:['Stand with feet wide, toes turned out, holding a chair if needed.','Lower with your knees tracking over your toes.','Rise, squeezing your glutes at the top.'], why:'Opens the hips and strengthens thighs and glutes.' },
    { n:'Counter push-ups', m:3, dose:'3 × 10', how:['Hands on a kitchen counter, walk your feet back.','Lower your chest toward the counter.','Press back up with a long spine.'], why:'Upper-body strength without lying on your back.' },
    { n:'Side-lying leg lifts', m:4, dose:'3 × 12 each side', how:['Lie on your side, bottom knee bent, pillow under your bump.','Lift your top leg straight to hip height.','Lower slowly.'], why:'Strengthens outer hips to reduce pelvic and lower-back pain.' },
    { n:'Bird-dog', m:4, dose:'3 × 8 each side', how:['Start on hands and knees.','Reach the opposite arm and leg long.','Keep your belly gently drawn in, like hugging baby toward your spine.'], why:'Deep core control without crunches, which you should avoid now.' },
    { n:'Band or bottle row', m:3, dose:'3 × 12', how:['Loop a band around a door handle or hold two bottles.','Pull your elbows back, squeezing your shoulder blades.','Release slowly.'], why:'Fights the forward slump as your bump grows.' },
    { n:'Pelvic tilts on all fours', m:3, dose:'2 × 10', how:['On hands and knees, back flat.','Breathe out and gently tuck your tailbone, rounding your lower back.','Breathe in and return to flat. No sagging.'], why:'One of the best moves for pregnancy back pain.' },
    { n:'Seated shoulder press', m:3, dose:'3 × 10', how:['Sit on a chair with back support, light weights or bottles at your shoulders.','Press overhead without arching your back.','Lower with control.'], why:'Arm strength for lifting car seats and babies.' },
    { n:'Kegels with breath', m:3, dose:'10 slow + 10 quick', how:['Breathe in and let your pelvic floor relax.','Breathe out and lift your pelvic floor.','Finish with 10 quick lifts.'], why:'Coordinating breath and pelvic floor protects against leaks.' },
    { n:'Swim or water walk', m:20, dose:'20 min', how:['Water walk or swim at an easy pace.','Avoid hot tubs and saunas.','Stay hydrated even in the pool.'], why:'Water supports your weight and can ease swelling.' },
    { n:'Step-ups', m:4, dose:'2 × 10 each leg', how:['Use the bottom stair and hold the rail.','Step up, bring the other foot up, step down.','Lead with the same leg for all reps, then switch.'], why:'Functional leg strength for stairs and carrying.' },
    { n:'Side plank from knees', m:3, dose:'3 × 15 s each side', how:['Lie on your side, propped on your forearm, knees bent.','Lift your hips so your body forms a line from knees to head.','Skip it if you feel pelvic pain or see your belly doming.'], why:'Strengthens the side core muscles that support your belly.' },
    { n:'Standing yoga flow', m:10, dose:'10 min', how:['Warrior II, 5 breaths each side.','Triangle pose with a hand on a block or chair, 5 breaths each side.','Goddess squat, 5 breaths. Use a wall for balance.'], why:'Builds strength and breath awareness while staying upright.' }
  ],
  t3: [
    { n:'Easy walk', m:15, dose:'15–20 min', how:['Walk at a conversational pace.','Take shorter strides if your pelvis feels sore.','Walk after meals to help with heartburn and blood sugar.'], why:'Keeps you moving without overdoing it.' },
    { n:'Supported deep squat', m:4, dose:'2 × 10', how:['Hold a counter with feet wide.','Lower as far as is comfortable, keeping heels down.','Rise slowly. Skip deep squats if baby is breech after 34 weeks.'], why:'Practises an active birth position and opens the pelvis.' },
    { n:'Birth ball hip circles', m:5, dose:'5 min', how:['Sit on a birth ball with feet wide.','Make slow circles and figure-8s with your hips.','Keep a hand on a table if needed.'], why:'Eases back pressure and encourages good positioning for baby.' },
    { n:'Wall push-ups', m:3, dose:'2 × 10', how:['Hands on a wall, body straight.','Lower slowly, then press back.','Keep breathing; never hold your breath.'], why:'Maintains upper-body strength for the newborn months.' },
    { n:'Side-lying clamshell', m:4, dose:'2 × 12 each side', how:['Lie on your side with a pillow under your bump.','Lift your top knee, keeping your feet together.','Lower slowly.'], why:'Supports your pelvis and eases pubic and hip pain.' },
    { n:'Standing pelvic tilts', m:3, dose:'2 × 10', how:['Stand with your back against a wall, knees soft.','Breathe out and flatten your lower back into the wall.','Release on the inhale.'], why:'Eases the lower-back ache of the final weeks.' },
    { n:'Pelvic floor release practice', m:4, dose:'10 breaths', how:['Sit or kneel comfortably.','As you breathe out slowly, let your pelvic floor soften and drop.','Imagine an opening flower: this is the letting-go you will use when pushing.'], why:'For birth, relaxing the pelvic floor matters as much as strengthening it.' },
    { n:'Seated band row', m:3, dose:'2 × 12', how:['Sit tall with a band looped around your feet or a door handle.','Pull your elbows back.','Release slowly.'], why:'Supports posture for feeding and carrying.' },
    { n:'Hands-and-knees rocking', m:3, dose:'3 min', how:['Kneel on all fours with knees under hips.','Rock gently forward and back.','Add slow hip sways side to side.'], why:'Takes pressure off your back and may help baby settle into a good position.' },
    { n:'Swim or water walk', m:20, dose:'20 min', how:['Move gently in the water.','Floating takes weight off your pelvis.','Get out slowly: you will feel heavy again on land.'], why:'The most comfortable cardio late in pregnancy.' },
    { n:'Labour breathing practice', m:5, dose:'5 min', how:['Breathe in through your nose for a count of 4.','Breathe out through your mouth for a count of 6 to 8.','Practise with your partner counting for you.'], why:'Long out-breaths calm you and help you work with contractions.' },
    { n:'Slow dance sway', m:10, dose:'10 min', how:['Put on calm music.','Lean into your partner or a counter and sway your hips.','Breathe slowly and let your shoulders drop.'], why:'A labour-coping move you can rehearse now. It also feels good today.' }
  ],
  pp1: [
    { n:'360° belly breathing', m:3, dose:'10 breaths', how:['Lie on your back or side, or sit supported.','Breathe in so your belly and ribs widen.','Breathe out slowly, feeling your belly gently draw in.'], why:'Reconnects your breath, deep core and pelvic floor after birth.', cs:'Hold a pillow over your incision for comfort.' },
    { n:'Gentle pelvic floor lifts', m:2, dose:'5 gentle lifts', how:['Breathe out and very gently lift your pelvic floor.','Hold 2 to 3 seconds, then fully relax.','Stop if it hurts or you have stitches that feel sore; try again in a few days.'], why:'Restores blood flow and early control.', cs:'Wait until your catheter is out, then start very gently.' },
    { n:'Short home walk', m:5, dose:'5–10 min', how:['Walk slowly around your home.','Add a few minutes each day if you feel well.','Rest when you need to; bleeding that gets heavier means slow down.'], why:'Supports circulation and lifts your mood.', cs:'Walking is encouraged; stand as tall as is comfortable.' },
    { n:'Ankle pumps', m:1, dose:'20 pumps', how:['Lie or sit with your legs out.','Point and flex your feet briskly.','Do this several times a day.'], why:'Keeps blood moving and helps lower the risk of clots.', cs:'Especially important after surgery.' },
    { n:'Shoulder blade squeezes', m:1, dose:'10 reps', how:['Sit tall, shoulders relaxed.','Squeeze your shoulder blades back and down.','Hold 3 seconds and release. Do this after each feed.'], why:'Resets posture after hours of feeding and holding.' },
    { n:'Neck stretches', m:1, dose:'1 min', how:['Drop one ear toward your shoulder.','Hold 15 seconds, then switch.','Finish by turning slowly to look over each shoulder.'], why:'Relieves the neck strain of looking down at your baby.' },
    { n:'Deep core hug', m:2, dose:'5 reps', how:['Lie on your side or back, knees bent.','Breathe out and gently draw your lower belly toward your spine.','Hold 3 seconds while breathing, then relax.'], why:'Starts gently reconnecting your deep abdominal muscles.', cs:'Very gently, and support your incision with a pillow.' },
    { n:'Log roll out of bed', m:1, dose:'Practise 3 times', how:['Bend your knees and roll onto your side as one unit.','Drop your legs off the bed.','Push up with your arms to sitting.'], why:'Protects your healing belly muscles every time you get up.', cs:'Use this every time for the first 6 weeks.' }
  ],
  pp2: [
    { n:'Stroller walk', m:15, dose:'10–20 min', how:['Walk at an easy pace with your baby.','Build up by a few minutes each day.','Stop and rest if bleeding increases.'], why:'Fresh air and movement are proven mood boosters postpartum.' },
    { n:'Heel slides', m:3, dose:'2 × 8 each leg', how:['Lie on your back, knees bent.','Breathe out, gently draw in your lower belly and slide one heel away.','Slide back and switch legs.'], why:'Rebuilds deep core control gently.', cs:'Start once walking feels easy and your incision is not sore.' },
    { n:'Glute bridge', m:3, dose:'2 × 8', how:['Lie on your back, knees bent, feet flat.','Breathe out, lift your pelvic floor, then lift your hips.','Lower slowly.'], why:'Wakes up the glutes that support your back while carrying.', cs:'Keep it small and slow; stop if it pulls at your scar.' },
    { n:'Sit-to-stand', m:3, dose:'2 × 8', how:['Sit on a sturdy chair.','Breathe out and stand up without using your hands if you can.','Sit down slowly.'], why:'Functional strength for getting up with your baby.' },
    { n:'Kegel progression', m:3, dose:'10 slow + 10 quick', how:['Lift and hold 5 seconds, then fully relax.','Add 10 quick lifts.','Do a set lying down, then another sitting.'], why:'Rebuilds pelvic floor strength to prevent leaks.' },
    { n:'Side-lying clamshell', m:3, dose:'2 × 10 each side', how:['Lie on your side, knees bent.','Lift your top knee, feet together.','Lower slowly.'], why:'Stabilises your pelvis.' },
    { n:'Cat-cow', m:2, dose:'1 min', how:['On hands and knees, breathe in and lift your chest.','Breathe out and round your back.','Move slowly with your breath.'], why:'Eases the back stiffness of feeding and rocking.', cs:'Try it after 3 to 4 weeks if kneeling is comfortable.' },
    { n:'Doorway row', m:2, dose:'2 × 10', how:['Hold a door frame with both hands and lean back slightly.','Pull your chest toward the frame.','Lower slowly.'], why:'Strengthens your upper back for carrying.' },
    { n:'Toe taps', m:3, dose:'2 × 6 each side', how:['Lie on your back with knees lifted over your hips.','Breathe out and slowly lower one toe to tap the floor.','Stop if your belly domes or bulges along the middle.'], why:'Progresses core strength while checking for separation.', cs:'Skip until after your 6-week check.' },
    { n:'Breathing pelvic tilts', m:2, dose:'2 × 8', how:['Lie on your back, knees bent.','Breathe out and gently tilt your pelvis to flatten your back.','Release as you breathe in.'], why:'Eases lower-back ache and engages your deep core.' }
  ],
  pp3: [
    { n:'Brisk walk', m:25, dose:'20–30 min', how:['Walk at a pace where talking is slightly harder.','Add a hill if it feels good.','Push the stroller with both hands and stand tall.'], why:'Rebuilds your fitness base before harder workouts.' },
    { n:'Bodyweight squat', m:4, dose:'3 × 10', how:['Feet shoulder-width apart.','Sit back and down, chest up.','Breathe out as you stand.'], why:'The foundation move for lifting your baby safely.' },
    { n:'Bridge march', m:3, dose:'2 × 8 each leg', how:['Hold a glute bridge.','Lift one foot a few centimetres, then set it down.','Alternate without your hips dropping.'], why:'Builds pelvic and core stability.' },
    { n:'Bird-dog', m:4, dose:'3 × 8 each side', how:['On hands and knees, reach the opposite arm and leg.','Keep your back flat like a tabletop.','Move slowly.'], why:'Rebuilds deep core strength safely.' },
    { n:'Incline push-up', m:3, dose:'3 × 10', how:['Hands on a counter or sofa arm.','Lower your chest with your body straight.','Press up.'], why:'Arm strength for all that carrying.' },
    { n:'Dead bug heel taps', m:3, dose:'2 × 8 each side', how:['Lie on your back, knees over hips, arms up.','Breathe out and lower one heel to tap the floor.','Watch for doming; if you see it, make the movement smaller.'], why:'Rebuilds core strength with a built-in separation check.' },
    { n:'Reverse lunge', m:4, dose:'2 × 8 each leg', how:['Step back and lower both knees.','Keep your front knee over your ankle.','Push through your front heel to return.'], why:'Single-leg strength and balance.' },
    { n:'Side plank from knees', m:3, dose:'3 × 15 s each side', how:['Prop on your forearm with knees bent.','Lift your hips into a straight line.','Breathe steadily.'], why:'Strengthens side core muscles.' },
    { n:'Babywearing walk', m:20, dose:'20 min', how:['Use a carrier with baby high and snug: close enough to kiss.','Walk at an easy pace.','Keep your shoulders back.'], why:'Adds gentle load and gives baby calm contact time.' },
    { n:'Bent-over row', m:3, dose:'3 × 10', how:['Hold light weights and hinge forward with a flat back.','Pull your elbows back.','Lower slowly.'], why:'Counters the rounded feeding posture.' },
    { n:'Squat with baby', m:3, dose:'2 × 8', how:['Hold baby close to your chest.','Squat slowly, sing a count out loud.','Rise and smile: it is a game for them too.'], why:'Strength training and bonding at the same time.' },
    { n:'The knack', m:2, dose:'10 practice lifts', how:['Before lifting anything, including baby, breathe out and lift your pelvic floor.','Then lift the object.','Make it a habit every time you lift.'], why:'Protects your pelvic floor from pressure during daily lifting.' }
  ],
  pp4: [
    { n:'Stroller intervals', m:25, dose:'25 min', how:['Walk 3 minutes easy, then 1 minute fast.','Repeat 5 to 6 times.','Keep good posture on the fast bits.'], why:'Builds fitness faster than steady walking.' },
    { n:'Goblet squat', m:4, dose:'3 × 10', how:['Hold a weight at your chest.','Squat to a comfortable depth.','Breathe out and lift your pelvic floor as you stand.'], why:'Builds leg and core strength together.' },
    { n:'Romanian deadlift', m:4, dose:'3 × 10', how:['Hold light weights in front of your thighs.','Hinge at the hips, sliding the weights down your legs with a flat back.','Squeeze your glutes to stand.'], why:'Protects your back for lifting car seats and toddlers.' },
    { n:'Push-ups', m:3, dose:'3 × 8', how:['On your knees or with hands on a bench.','Lower your chest with your body straight.','Press up while breathing out.'], why:'Full upper-body strength.' },
    { n:'Front plank', m:3, dose:'3 × 20 s', how:['Start from your knees, then progress to your toes.','Keep your back flat and breathe.','Stop if you see doming or feel pelvic heaviness.'], why:'Tests and builds core strength.' },
    { n:'Split squat', m:4, dose:'3 × 8 each leg', how:['Stand in a long stride.','Lower your back knee toward the floor.','Drive up through your front heel.'], why:'Strength and balance for a mobile baby.' },
    { n:'Single-leg bridge', m:3, dose:'2 × 8 each leg', how:['Lie in bridge position and lift one foot.','Press your hips up through the planted heel.','Lower slowly.'], why:'Balances left and right hip strength.' },
    { n:'Band row', m:3, dose:'3 × 12', how:['Anchor a band at chest height.','Pull your elbows back.','Pause, then release slowly.'], why:'Keeps your shoulders healthy through months of carrying.' },
    { n:'Low-impact circuit', m:12, dose:'12 min', how:['40 seconds each: step jacks, squats, knee lifts, wall push-ups.','Rest 20 seconds between moves.','Repeat three rounds.'], why:'Cardio and strength in one short session during nap time.' },
    { n:'Suitcase carry', m:3, dose:'3 × 30 s each side', how:['Hold a heavy bag in one hand.','Walk tall without leaning.','Switch hands.'], why:'Trains your core for real-life carrying.' },
    { n:'Step-ups', m:4, dose:'3 × 10 each leg', how:['Use a sturdy step.','Drive up through your heel.','Step down with control.'], why:'Leg power for stairs and hills with the stroller.' },
    { n:'Yoga flow', m:10, dose:'10 min', how:['Downward dog, 5 breaths.','Low lunge, 5 breaths each side.','Child\'s pose, 1 minute.'], why:'Mobility and a calm reset.' }
  ]
};
